# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

# Repo Action 페이지에 나타날 이름 
name: Web2gether Homepage Deploy

# Event Trigger
# master branch에 push 또는 pull request가 발생할 경우 동작
# branch 단위 외에도, tag나 cron 식 등을 사용할 수 있음 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    # Task의 sequence를 명시한다.
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build
    
    - name: Deliver File
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_SSH_HOST }}
        username: ${{ secrets.REMOTE_SSH_USERNAME }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        port: ${{ secrets.REMOTE_SSH_PORT }}
        source: "build/libs/w2gHp.jar, script/*.sh"
        target: "source"

    - name: Start server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_SSH_HOST }}
        username: ${{ secrets.REMOTE_SSH_USERNAME }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        script: |
          chmod +x /home/ubuntu/source/script/start.sh        
          chmod +x /home/ubuntu/source/script/health.sh
          chmod +x /home/ubuntu/source/script/profile.sh
          chmod +x /home/ubuntu/source/script/stop_old_one.sh
          chmod +x /home/ubuntu/source/script/switch.sh
          . /home/ubuntu/source/script/start.sh
    
    - name: Validate server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_SSH_HOST }}
        username: ${{ secrets.REMOTE_SSH_USERNAME }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        script: |        
          . /home/ubuntu/source/script/health.sh
          . /home/ubuntu/source/script/stop_old_one.sh
